version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - pip3 install awscli --upgrade --user

  build:
    commands:

artifacts:
  discard-paths: yes  # yamllint disable-line rule:truthy
  files:
    - target/*
    - appspec.yml
